export const FETCH_ABANDONED_CARTS_REQUEST = 'FETCH_ABANDONED_CARTS_REQUEST';
export const FETCH_ABANDONED_CARTS_SUCCESS = 'FETCH_ABANDONED_CARTS_SUCCESS';
export const FETCH_ABANDONED_CARTS_FAILURE = 'FETCH_ABANDONED_CARTS_FAILURE';