export const FETCH_REFERENCE_DATA_REQUEST = 'FETCH_REFERENCE_DATA_REQUEST';
export const FETCH_REFERENCE_DATA_SUCCESS = 'FETCH_REFERENCE_DATA_SUCCESS';
export const FETCH_REFERENCE_DATA_FAILURE = 'FETCH_REFERENCE_DATA_FAILURE';