export const FETCH_TEMPLATES_REQUEST = 'FETCH_TEMPLATES_REQUEST';
export const FETCH_TEMPLATES_SUCCESS = 'FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAILURE = 'FETCH_TEMPLATES_FAILURE';

export const FETCH_TEMPLATE_USAGE_REQUEST = 'FETCH_TEMPLATE_USAGE_REQUEST';
export const FETCH_TEMPLATE_USAGE_SUCCESS = 'FETCH_TEMPLATE_USAGE_SUCCESS';
export const FETCH_TEMPLATE_USAGE_FAILURE = 'FETCH_TEMPLATE_USAGE_FAILURE';

export const SEND_TEMPLATE_REQUEST = 'SEND_TEMPLATE_REQUEST';
export const SEND_TEMPLATE_SUCCESS = 'SEND_TEMPLATE_SUCCESS';
export const SEND_TEMPLATE_FAILURE = 'SEND_TEMPLATE_FAILURE';

export const SEND_TEMPLATE_TO_NUMBER_REQUEST = 'SEND_TEMPLATE_TO_NUMBER_REQUEST';
export const SEND_TEMPLATE_TO_NUMBER_SUCCESS = 'SEND_TEMPLATE_TO_NUMBER_SUCCESS';
export const SEND_TEMPLATE_TO_NUMBER_FAILURE = 'SEND_TEMPLATE_TO_NUMBER_FAILURE';